spring:
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/table.sql
      data-locations:
        - classpath:db/data.sql
logging:
  level:
    org.hibernate:
      sql:
        debug
      type:
        descriptor:
          sql:
            BasicBinder: trace

#file.dir: '/Users/joonheejeong/Desktop/fastcampus/KDTBE5_Java/files/'
